[package]
name = "Angular-CookBook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook-admonish = "1.10.0"
mdbook-catppuccin = "0.2.0"
mdbook-i18n-helpers = "0.1.0"