[package]
name = "angular-cookbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "^0.4.34"
mdbook-admonish = "^1.10.2"
mdbook-i18n-helpers = "^0.2.1"