name: Install mdbook and dependencies

description: Install mdbook with the dependencies we need.

runs:
  using: composite
  steps:
    # The --locked flag is important for reproducible builds. It also
    # avoids breakage due to skews between mdbook and mdbook-svgbob.

    - name: Install mdbook-svgbob
      run: cargo install mdbook-svgbob --locked --version 0.2.1 --force
      shell: bash

    - name: Install mdbook-i18n-helpers
      run: cargo install mdbook-i18n-helpers --locked --version 0.3.0 --force
      shell: bash

    - name: Install mdbook-admonish
      run: cargo install mdbook-admonish --locked --version 1.13.1 --force
      shell: bash
